// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Zippysoft.CodeFirst.DAL.CompiledModels
{
    [DbContext(typeof(BetterDbContext))]
    public partial class BetterDbContextModel : RuntimeModel
    {
        static BetterDbContextModel()
        {
            var model = new BetterDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static BetterDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
