// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Zippysoft.CodeFirst.DAL.CompiledModels
{
    public partial class BetterDbContextModel
    {
        partial void Initialize()
        {
            var aduser = AduserEntityType.Create(this);

            AduserEntityType.CreateAnnotations(aduser);

            AddAnnotation("ProductVersion", "7.0.11");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
